name: Build Solution

on:
  pull_request:
    branches:
      - main

env:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet build
        run: |
          dotnet restore Api/BccPay.Core.sln
          dotnet build Api/BccPay.Core.Domain/BccPay.Core.Domain.csproj -c ${{ env.BUILD_CONFIGURATION }}

      - name: Dashboard angular build
        run: |
          cd ./UI/dashboard/
          npm install
          npm run build

      - name: Webcomponent build
        run: |
          cd ./WebComponents/bcc-pay/
          npm install
          npm run build
